### ISSUE TITLE
Motionbox crash on start

### ISSUE THREAD

**Issue by TheDalaiAlpaca** [G-P-L/AUR#1]
Hi. I installed the motionbox 1.6.0.4-2 package from the AUR, however it doesn't start. Instead it gives this error:  
```
Starting MotionBox...
/opt/MotionBox/MotionBox: error while loading shared libraries: libidn.so.11: cannot open shared object file: No such file or directory
```
I tried installing `libidn`, but it was already installed (libidn-1.35-2), however there is no libidn.so.11
```
find / -name libidn*.so 2> /dev/null
/usr/lib/libidn.so
/usr/lib/libidn2.so
```

**Comment by G-P-L** [comment]
Hi!
Thanks for reporting this issue. It turned out that my system has libidn.so.11 under /usr/lib and
`pacman -Qo libidn.so.11` said this file belongs to the libidn11 package from the community repository.
The PKGBUILD already updated and version 1.6.0.4-3 has libidn11 as dependency.

**Comment by TheDalaiAlpaca** [comment]
Thanks, it works!
