### ISSUE TITLE
Validation Error

### ISSUE THREAD

**Issue by lediraison-a** [G-P-L/AUR#3]
Hello, 
I tried to install the aur package but I get an error 'validating the source MotionBox-1.6.0-12-linux64.tar.gz with sha256sums…'.
I saw that you made the changes accordingly on the PKGBUILD a few days ago but the validation part still fail for me.

> alban@albanArch motionbox-bin makepkg -si
==> Création du paquet motionbox-bin 1.6.0.12-2 (mer. 14 avril 2021 23:19:03)
==> Vérification des dépendances pour l’exécution…
==> Vérification des dépendances pour la compilation…
==> Récupération des sources…
  -> MotionBox-1.6.0-12-linux64.tar.gz trouvé
  -> MotionBox.desktop trouvé
  -> MotionBox.png trouvé
==> Validation des fichiers source avec sha256sums…
    MotionBox-1.6.0-12-linux64.tar.gz ... ÉCHEC
    MotionBox.desktop ... Réussite
    MotionBox.png ... Réussite
==> ERREUR : Un ou plusieurs fichiers ne sont pas valides !

**Comment by G-P-L** [comment]
Hi,
thank you for reporting it. I updated the PKGBUILD with the new checksum. The maintainer of the package often repackaging the source without version number change, which causing the sha256 sum differences. I many times did not notice this change. In this case it is a temporary option to change the sha265 of the tar.gz file to SKIP in the PKGBUILD to bypass this issue, altough it is less safer.

**Comment by lediraison-a** [comment]
Ok. Thank's ! validation checking work's
